### ISSUE TITLE
Output of MMR, LexRank and TextRank ?

### ISSUE THREAD

**Issue by yashkumaratri** [Alex-Fabbri/Multi-News#8]
Can you provide output for the above three algorithms too?

**Comment by Alex-Fabbri** [comment]
I will update the output within the next couple of days.

**Comment by Alex-Fabbri** [comment]
Sorry for the delay -- was traveling. I just uploaded the extractive model output when run on the full input (which was what we did in the paper) and on the truncated input (which we didn't do in the paper mainly because we at first were focusing on extractive models as input to the abstractive models, but the results for running on the truncated input are actually very good in terms of ROUGE). I will be updating the README of the repo with updated ROUGE scores for both inputs. Closing for now but feel free to open with additional questions.
